name: stater
description: library for state management with Firebase like API with support for caching of server data locally
version: 0.1.0-alpha.2+2
homepage:

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  async: ^2.8.2
  collection: ^1.16.0
  get_storage: ^2.0.3
  http: ^0.13.4
  meta: ^1.7.0
  rxdart: ^0.27.3
  uuid: ^3.0.6
  fast_immutable_collections: ^7.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.2.0
  shelf: ^1.3.1
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  path: ^1.8.1

# The following section is specific to Flutter packages.
flutter:
