name: stater
description: library for state management with Firebase like API with support for caching of server data locally
version: 0.1.0-alpha.1+1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  async: ^2.8.2
  collection: ^1.16.0
  dio: ^4.0.6
  get_storage: ^2.0.3
  http: ^0.13.4
  meta: ^1.7.0
  rxdart: ^0.27.3
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  # plugin:
  #   platforms:
  #     android:
  #       package: com.rajkovukovic.stater
  #       pluginClass: StaterPlugin
  #     ios:
  #       pluginClass: StaterPlugin
  #     linux:
  #       pluginClass: StaterPlugin
  #     windows:
  #       pluginClass: StaterPluginCApi
  #     web:
  #       pluginClass: StaterWeb
  #       fileName: stater_web.dart
